---
root: true
env:
  browser: true
  es2022: true
  node: true
ignorePatterns:
  - /*.js
  - /vitest.config.ts
plugins:
  - '@typescript-eslint'
  - tailwindcss
extends:
  - eslint:recommended
  - plugin:svelte/recommended
  - standard-with-typescript
  - eslint-config-prettier
  - plugin:tailwindcss/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  sourceType: module
  ecmaVersion: 2022
  extraFileExtensions: ['.svelte']
  project: './tsconfig.json'
overrides:
  - files: '*.svelte'
    parser: svelte-eslint-parser
    parserOptions:
      parser: '@typescript-eslint/parser'
      project: './tsconfig.json'
rules:
  # eslint
  semi: off

  # @typescript-eslint
  '@typescript-eslint/array-type':
    - error
    - default: array
      readonly: array
  '@typescript-eslint/restrict-template-expressions':
    - error
    - allowNumber: true
      allowBoolean: true
      allowAny: true
      allowNullish: false
      allowRegExp: true
  '@typescript-eslint/no-unnecessary-condition': error
  '@typescript-eslint/consistent-type-imports': error
  '@typescript-eslint/no-import-type-side-effects': error
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/no-misused-promises': off
  '@typescript-eslint/no-non-null-assertion': off
  '@typescript-eslint/no-invalid-void-type': off
  '@typescript-eslint/prefer-ts-expect-error': off
  '@typescript-eslint/ban-types': off
  '@typescript-eslint/ban-ts-comment': off

  # Tailwind
  tailwindcss/no-custom-classname:
    - warn
    - whitelist:
        - material-icons
  tailwindcss/enforces-negative-arbitrary-values: off
