name: mediakit
version: '3'
volumes:
  postgres:
services:
  postgres:
    image: postgres:alpine3.18
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    ports:
      - 5432:5432
